<a href="https://colab.research.google.com/github/aperfilyeva/anna_data690/blob/main/assignment_05/Assignment_5_Part_4_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 5 Part 4 Numpy

 - Anna Perfilyeva
 - 3/4/2022

In [1]:
import sys
import numpy as np

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])

In [5]:
a[0], a[1]

(1, 2)

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1]

array([2, 3])

In [9]:
a[::2]

array([1, 3])

In [10]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [11]:
b[[0, 2, -1]]

array([0., 1., 2.])

**Array Types**

In [12]:
a

array([1, 2, 3, 4])

In [13]:
a.dtype

dtype('int64')

In [14]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [15]:
b.dtype

dtype('float64')

In [16]:
np.array([1, 2, 3, 4], dtype=np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([1., 2., 3., 4.])

In [17]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [18]:
c = np.array(['a', 'b', 'c'])

In [19]:
c.dtype

dtype('<U1')

In [20]:
d = np.array([{'a':1}, sys])

In [21]:
d.dtype

dtype('O')

## Dimensions and Shapes

In [22]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [25]:
A.shape

(2, 3)

In [23]:
A.size

6

In [26]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [27]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [28]:
B.shape

(2, 2, 3)

In [29]:
B.size

12

In [31]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  import sys


In [32]:
C.dtype

dtype('O')

In [35]:
c.shape

(3,)

In [36]:
c.size

3

In [37]:
type(C[0])

list

## Indexing and Slicing of Matrices

In [39]:
A = np.array([
    [1, 2, 3],   #0
    [4, 5, 6],   #1
    [7, 8, 9]    #2
])

In [40]:
A[1]

array([4, 5, 6])

In [41]:
A[1][0]

4

In [42]:
A[1, 0]

4

In [43]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [45]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [46]:
A[:2, 2:]

array([[3],
       [6]])

In [47]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
A[1] = np.array([10, 10, 10])

In [51]:
A[2] = 99

In [52]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

## Summary Statistics

In [53]:
a = np.array([1, 2, 3, 4])

In [54]:
a.sum()

10

In [55]:
a.mean()

2.5

In [56]:
a.std()

1.118033988749895

In [57]:
a.var()

1.25

In [58]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [59]:
a.sum()

10

In [ ]:
a.mean()

In [60]:
a.std()

1.118033988749895

In [61]:
A.sum(axis=0)

array([12, 15, 18])

In [62]:
A.sum(axis=1)

array([ 6, 15, 24])

In [63]:
A.mean(axis=0)

array([4., 5., 6.])

In [64]:
A.mean(axis=1)

array([2., 5., 8.])

In [65]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [66]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [67]:
## Broadcasting and Vectorized operations

In [68]:
a = np.arange(4)

In [69]:
a

array([0, 1, 2, 3])

In [70]:
a+10

array([10, 11, 12, 13])

In [71]:
a*10

array([ 0, 10, 20, 30])

In [72]:
a+=100

In [73]:
a

array([100, 101, 102, 103])

In [74]:
l = [0, 1, 2, 3]

In [75]:
[i * 10 for i in l]

[0, 10, 20, 30]

## Broadcasting and Vectorized operations (Masks)

In [124]:
a = np.arange(4)

In [125]:
a

array([0, 1, 2, 3])

In [126]:
a + 10

array([10, 11, 12, 13])

In [127]:
a * 10

array([ 0, 10, 20, 30])

In [95]:
a

array([0, 1, 2, 3])

In [96]:
a += 100

In [97]:
a

array([100, 101, 102, 103])

In [98]:
l = [0, 1, 2, 3]

In [99]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [100]:
a = np.arange(4)

In [101]:
a

array([0, 1, 2, 3])

In [102]:
b = np.array([10, 10, 10, 10])

In [103]:
b

array([10, 10, 10, 10])

In [104]:
a + b

array([10, 11, 12, 13])

In [105]:
a * b

array([ 0, 10, 20, 30])

## Boolean arrays



In [106]:
a = np.arange(4)

In [107]:
a

array([0, 1, 2, 3])

In [108]:
a[0], a[-1]

(0, 3)

In [109]:
a[[0, -1]]

array([0, 3])

In [110]:
a[[True, False, False, True]]

array([0, 3])

In [111]:
a

array([0, 1, 2, 3])

In [112]:
a >= 2

array([False, False,  True,  True])

In [113]:
a[a >= 2]

array([2, 3])

In [114]:
a.mean()

1.5

In [115]:
a[a > a.mean()]

array([2, 3])

In [116]:
a[~(a > a.mean())]

array([0, 1])

In [117]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [118]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [119]:
A = np.random.randint(100, size=(3,3))

In [120]:
A

array([[25, 73, 41],
       [ 9,  4, 98],
       [37, 64, 59]])

In [121]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([25, 41,  4, 37, 59])

In [122]:
A > 30

array([[False,  True,  True],
       [False, False,  True],
       [ True,  True,  True]])

In [123]:
A[A > 30] 

array([73, 41, 98, 37, 64, 59])

### **Linear Algebra**

In [129]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [130]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [131]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [132]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [133]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [134]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [135]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

## Size of objects in Memory

In [136]:
sys.getsizeof(1)

28

In [137]:
sys.getsizeof(10**100)

72

In [140]:
np.dtype(int).itemsize

8

In [141]:
np.dtype(float).itemsize

8

**Lists are even larger**

In [ ]:
# A one-element list
sys.getsizeof([1])

80

In [ ]:
# An array of one element in numpy
np.array([1]).nbytes

8

**And performance is also important**

In [146]:
l = list(range(100000))

In [147]:
a = np.arange(100000)

In [144]:
%time np.sum(a ** 2)

CPU times: user 129 µs, sys: 17 µs, total: 146 µs
Wall time: 149 µs


332833500

In [145]:
%time sum([x ** 2 for x in l])

CPU times: user 494 µs, sys: 0 ns, total: 494 µs
Wall time: 503 µs


332833500

## Useful Numpy functions

random

In [148]:
np.random.random(size=2)

array([0.99718745, 0.55431587])

In [149]:
np.random.normal(size=2)

array([ 0.73937805, -1.04754949])

In [150]:
np.random.rand(2, 4)

array([[0.71708352, 0.46887247, 0.89835225, 0.99868218],
       [0.14241564, 0.95245918, 0.73368077, 0.12303315]])

arange

In [151]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [153]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

reshape

In [154]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [155]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

linspace

In [156]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [157]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [158]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

zeros, ones, empty

In [159]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [160]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [161]:
np.zeros((3, 3), dtype=np.int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [162]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [163]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [164]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [165]:
np.empty((2,2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

identity and eye

In [166]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [167]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [168]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [169]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [170]:
np.eye(8, 4, k=3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [171]:
"Hello World"[6]

'W'